# Generated by Django 5.2 on 2025-08-22 11:22

import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('dealerName', models.CharField(max_length=50)),
                ('dealerMobile', models.CharField(default=testapp.models.generate_indian_number, max_length=13)),
                ('address', models.TextField()),
                ('creditLimit', models.IntegerField()),
                ('usedLimit', models.IntegerField()),
                ('paidLimit', models.IntegerField()),
                ('availableLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(default=testapp.models.generate_indian_number, max_length=13)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('productName', models.CharField(max_length=100)),
                ('totalBill', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KnrDealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50)),
                ('dealerName', models.CharField(max_length=50)),
                ('dealerMobile', models.CharField(default=testapp.models.generate_indian_number, max_length=13)),
                ('shopAddress', models.TextField()),
                ('creditLimit', models.IntegerField()),
                ('usedLimit', models.IntegerField()),
                ('paidLimit', models.IntegerField()),
                ('availableLimit', models.IntegerField()),
            ],
        ),
    ]
