# Generated by Django 5.2 on 2025-08-22 11:23

import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directcompanies',
            name='dealerMobile',
            field=models.CharField(default=testapp.models.generate_indian_number, max_length=14),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(default=testapp.models.generate_indian_number, max_length=14),
        ),
        migrations.AlterField(
            model_name='knrdealers',
            name='dealerMobile',
            field=models.CharField(default=testapp.models.generate_indian_number, max_length=14),
        ),
    ]
