# Generated by Django 5.2 on 2025-08-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_directcompanies_dealermobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knrdealers',
            old_name='shopName',
            new_name='shopname',
        ),
    ]
